# Generated by Django 2.2.7 on 2019-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0002_auto_20191127_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Longitude',
            field=models.FloatField(),
        ),
    ]
