# Generated by Django 2.2.7 on 2019-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0004_auto_20191203_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Approaches'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Chasing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Climbing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Eating'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Foraging'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Indifferent'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Kuks'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Moans'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Other_Activities',
            field=models.BooleanField(default=False, help_text='Other_Activities'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Quaas'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Running',
            field=models.BooleanField(default=False, help_text='Running'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Runs from'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Tail Flags'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Tail_twitches',
            field=models.BooleanField(default=False, help_text='Tail Twitches'),
        ),
    ]
