# Generated by Django 2.2.7 on 2019-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0005_auto_20191207_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Location',
            field=models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location', max_length=100),
        ),
    ]
