# Generated by Django 2.2.7 on 2019-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0006_auto_20191207_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Other_Activities',
            field=models.CharField(help_text='Other activities', max_length=100),
        ),
    ]
