# Generated by Django 2.2.7 on 2019-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0007_auto_20191207_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Unique_Squirrel_Id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=30, primary_key=True, serialize=False),
        ),
    ]
