# Generated by Django 2.2.7 on 2019-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel_Sightings', '0008_auto_20191207_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', ''), ('?', '?')], default='', help_text='Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Other_Activities',
            field=models.CharField(default='', help_text='Other activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Primary_Fur_Color',
            field=models.CharField(choices=[('black', 'Black'), ('cinnamon', 'Cinnamon'), ('gray', 'Gray')], default='black', help_text='Primary Fur Color', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Specific_Location',
            field=models.CharField(default='', help_text='Specific Location', max_length=30),
        ),
    ]
